### ISSUE TITLE
Version 1.14.1 causes Polymer to not load in Firefox 43.0.3

### ISSUE THREAD

**Issue by JamesFigler** [Polymer/vulcanize#299]
We get the following errors when rendering our app in Firefox after upgrading to 1.14.1. Rolling back to 1.14.0 fixes the issue. This problem does not affect Chrome. 
```
TypeError: document.registerElement is not a function
 localhost:8080:775:1
TypeError: Polymer.Base._getExtendedPrototype is not a function
 localhost:8080:538:8
TypeError: this._desugarBehaviors is not a function
 localhost:8080:648:1
TypeError: this._desugarBehaviors is not a function
 localhost:8080:648:1
TypeError: this._desugarBehaviors is not a function
 localhost:8080:648:1
TypeError: this._desugarBehaviors is not a function
 localhost:8080:648:1
TypeError: Polymer.Base._getExtendedPrototype is not a function
 localhost:8080:538:8
TypeError: this._desugarBehaviors is not a function
 localhost:8080:648:1
TypeError: this._desugarBehaviors is not a function
 localhost:8080:648:1
TypeError: this._desugarBehaviors is not a function
 localhost:8080:648:1
TypeError: this._desugarBehaviors is not a function
 localhost:8080:648:1
TypeError: this._desugarBehaviors is not a function
 localhost:8080:648:1
TypeError: this._desugarBehaviors is not a function
 localhost:8080:648:1
TypeError: this._desugarBehaviors is not a function
 localhost:8080:648:1
TypeError: this._desugarBehaviors is not a function
 localhost:8080:648:1
TypeError: this._desugarBehaviors is not a function
 localhost:8080:648:1
TypeError: this._desugarBehaviors is not a function
 localhost:8080:648:1
TypeError: this._desugarBehaviors is not a function
 localhost:8080:648:1
TypeError: Polymer.Base._getExtendedPrototype is not a function
 localhost:8080:538:8
TypeError: this._desugarBehaviors is not a function
 localhost:8080:648:1
TypeError: this._desugarBehaviors is not a function
 localhost:8080:648:1
TypeError: this._desugarBehaviors is not a function
 localhost:8080:648:1
TypeError: this._desugarBehaviors is not a function
 localhost:8080:648:1
TypeError: this._desugarBehaviors is not a function
 localhost:8080:648:1
TypeError: this._desugarBehaviors is not a function
 localhost:8080:648:1
TypeError: this._desugarBehaviors is not a function
 localhost:8080:648:1
TypeError: this._desugarBehaviors is not a function
 localhost:8080:648:1
TypeError: this._desugarBehaviors is not a function
 localhost:8080:648:1
TypeError: this._desugarBehaviors is not a function
 localhost:8080:648:1
TypeError: this._desugarBehaviors is not a function
 localhost:8080:648:1
TypeError: views.select is not a function
```

**Comment by azakus** [comment]
Please try with `v1.14.2` or later, this is probably related to #297

**Comment by StephenTurley** [comment]
Getting the same error with v1.14.5

**Comment by garlicnation** [comment]
@StephenTurley Is there any way you could provide an example of your project?

@azakus and I tracked down a very similar issue that was caused by some dependencies not being listed in HTML imports. Earlier versions of vulcanize would occasionally mask a missing HTML import as long as the dependency existed somewhere else in the project.

**Comment by StephenTurley** [comment]
Its a private repo and I couldn't share it, but I'll check through the imports and see if anything is coming in transitively. If that doesn't work, I'll try to reproduce it in a public repo.

**Comment by StephenTurley** [comment]
Also, should probably say that I'm working on the same project with @JamesFigler

**Comment by garlicnation** [comment]
@StephenTurley I don't know how to take this further without a reproduction, unfortunately.

**Comment by StephenTurley** [comment]
Ahh sorry, We have just kept the old version of Vulcanize and it has worked well. We are starting another app that will have a separate pipeline. I will use the newest version of vulcanize there and see if the problem pops back up.

**Comment by StephenTurley** [comment]
I've upgraded to 1.14.8 and everything is working. I think you can close this. Tested on Firefox 43.0.4
